name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2
    - name: Set up Golang
      uses: actions/setup-go@v2.1.3
      with:
        go-version: '1.14'
    - name: Install dependencies
      run: bundle install
    - name: Rails Tests
      run: bundle exec rails test
      env:
        DATABASE_URL: postgres://postgres:5432/cnb-registry-api-test?sslmode=disable
    - name: Set up Golang env
      run: |
        echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      shell: bash
    - name: Golang Tests
      run: |
        go test ./...
